### ISSUE TITLE
Maintaining minimum replicas of a K8s deployment on "on-demand" NodePool

### ISSUE THREAD

**Issue by arunnalpet** [kubernetes-sigs/karpenter#1104] opened 2024-03-15 09:21 UTC
### **What problem are you trying to solve?**
Provision initial few pod instances of a particular `K8s Deployment` to on-demand NodePool, then the rest of it to spot NodePool.

Here I am talking about two NodePools:
- `on-demand NodePool` --> NodePool that provisions only on-demand instances.
- `spot NodePool` --> NodePool that provisions spot instances with fallback to on-demand configured.

**Requirement/scenario**:

- Consider the customer is deploying 10 applications (K8s deployments). For each application, they would want to ensure and deploy initial few pods on to "**on-demand**" only NodePool. Rest of the replicas can be deployed on spot NodePool.
- The motive here is to ensure that minimum replicas of a each deployment, is always running on "on-demand" NodePool, while additional replicas can be running either on "spot" or on-demand NodePool.

### **How important is this feature to you?**
I have had several customers requesting this capability, to ensure minimum replicas are always available on "on-demand" instances.

### **Proposal**
For each k8s deployment, attach a label(or karpenter hint) `minOnDemand`. For example `minOnDemand=3`. With this karpenter should schedule a minimum of 3 pods to on-demand NodePool, and rest with subsequent NodePool that matches the needs. Just a thought. There could be other approaches to implement this.

-----

#### Through Weighted NodePool. Its only half of a solution.
- We can have 2 NodePools. One with "on-demand" with higher weight and another "spot" with lower/default weight. These Weights can ensure, that the initial pods _**across all Deployments**_ will be served on weighted nodepool.
- With this approach, the NodePool with the highest weight (for ex: on-demand NodePool), will will take priority and serve as long as it reaches "cpu limits" of the NodePool. Assume, cpu limits are reached, and there is a new application that's being deployed, then it will be scheduled on to subsequent "spot" NodePool. In this case, minimum replicas of new application, is not guaranteed to be deployed on "on-demand" NodePool.

#### Multiple Provisioners
- Another workaround is to have 2 deployments of same applications. One explicitly selecting on-demand NodePool, another explicitly selecting spot NodePool. This introduces lot of operational overhead, especially during automated deployments.

cc: @gowthasa

---------

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by runningman84** [comment] 2024-03-15 12:41
I think your proposal will be difficult to implement because karpenter does not decide about pod placement it just fulfills pending pod requests.

**Comment by jmdeal** [comment] 2024-03-15 23:28
Like @runningman84 said, Karpenter does not schedule pods, it brings up new capacity when it detects unschedulable pods in the cluster. As far as I know Kubernetes doesn't have any form of scheduling constraint that works like this. The closest would be topologySpreadConstraints but that doesn't offer a method to ensure the first pods are placed in a given domain. Is there any reason you care about the first n pods being scheduled to on-demand vs a certain percentage? It is possible to achieve the latter today with two nodepools and topologySpreadConstraints: [example](https://karpenter.sh/docs/concepts/scheduling/#on-demandspot-ratio-split).

**Comment by arunnalpet** [comment] 2024-03-18 10:45
Thanks @runningman84 @jmdeal.. Point taken that Karpenter cannot take part in scheduling decisions.. 

In this scenario, customer wants to optimize costs by running everything on spot. But want to run minimal replicas of each deployment on on-demand nodes, so that if the spot instances gets terminated, on-demand replicas keep running.

**Comment by runningman84** [comment] 2024-03-18 12:45
In your case I would just use two deployments one is node selector = ondemand the other with no node selector... and an hpa only configured for the second deployment...

**Comment by arunnalpet** [comment] 2024-03-19 08:58
Right.. If it was fewer applications, would have settled for having multiple deployments per application. But if we are looking at 100s, then it is challenging.

I'm now inclined towards exploring either custom scheduler or mutating web-hooks to achieve the same..

**Comment by runningman84** [comment] 2024-03-19 09:57
I would recommend a mutating webhook in this case: https://kmitevski.com/kubernetes-mutating-webhook-with-python-and-fastapi/ 
If you have some working example please share this.

**Comment by jonathan-innis** [comment] 2024-05-14 04:29
I recognize there's been some conversation on here already, but coming around to this one, I'm going to close this one as a duplicate of #757 since this is effectively wanting a percentage of your deployment on a specific capacity type.

**Closed by jonathan-innis** 2024-05-14 04:29 UTC
Labels: kind/feature, needs-triage

**Comment by jonathan-innis** [comment] 2024-05-14 04:31
There's some ideas around how to do this kind of thing covered in the docs [here](https://karpenter.sh/docs/concepts/scheduling/#on-demandspot-ratio-split) but it's definitely non-perfect and doesn't maintain the capacity split on scale-down (since TSC doesn't handle this scale-down case gracefully)

**Comment by arunnalpet** [comment] 2024-05-14 17:45
Agree that ratio-split isn't perfect solution. Will follow up on #757 which is a similar request.. 👍
