### ISSUE TITLE
Metrics inconsistency between karpenter replicas 

### ISSUE THREAD

**Issue by trojaond** [kubernetes-sigs/karpenter#1450] opened 2024-07-19 13:24 UTC
### Description

**Observed Behavior**:
When Karpenter is deployed, it creates 2 replicas. One of these replicas is elected as the leader, while the other remains in standby mode. When configuring Prometheus scraping, you have the option to scrape either from the service or directly from the endpoints (pods).

- Scraping from the leader pod returns the full list of metrics with accurate values, such as:
`karpenter_cluster_state_node_count 6`

- However, scraping from the standby pod also provides values, but they are incorrect, resulting in:
`karpenter_cluster_state_node_count 0`

This inconsistency becomes problematic when scraping from the service, as the destination can change arbitrarily. This can lead to inconsistent scraped data and result in sudden reports of 0 nodes in our dashboard if it is configured to display the latest scraped value.

Expected Behavior:
Metrics should not be displayed at all from the standby pod.
Metrics should be consistent with those from the leader pod.
**Expected Behavior**:
- Metrics should not be displayed at all from the standby pod.
or
- Metrics should be consistent with those from the leader pod.

**Reproduction Steps** (Please include YAML):
1. Port forward to leader pod and open to local port `8004` curl `localhost:8004/metrics`
2. Port forward to standby pod and open to local port `8005` curl `localhost:8005/metrics`
3. Compare the metrics and see the difference

**Versions**:
- Chart Version: 0.36.2
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment] 2024-07-25 02:09
>However, scraping from the standby pod also provides values, but they are incorrect, resulting in:
karpenter_cluster_state_node_count 0

are you saying that all metrics on the standby pod are 0'd out? or that they're just incorrect, and can be a non-zero value?

**Comment by njtran** [comment] 2024-07-25 02:09
@jigisha620 can you take a look a this?

**Comment by jigisha620** [comment] 2024-07-25 17:16
@trojaond I have been able to reproduce this issue. I am consistently seeing `karpenter_cluster_state_node_count` as 0 when scraping from standby pod as well as the service.

**Comment by liangyuanpeng** [comment] 2024-07-26 07:36
Other option is you can drop the metrics `karpenter_cluster_state_node_count ` when metrics `leader_election_master_status` is 0 .

**Comment by jigisha620** [comment] 2024-07-26 20:43
Our recommendation is to not scrape metrics from the service but from the karpenter pods. Another alternative is to use prometheus service discovery.

**Comment by varxnnn** [comment] 2024-08-09 11:04
Can you point me towards a working example? 
We have Grafana Agents, and we use `discovery.kubernetes`(`discovery.river`) to query metrics. As per [this](https://arc.net/l/quote/bviuhurb), we might be limited to just nodes/pods/services, etc. I get that we have the `leader_election_master_status` as 1 in the leader pod, but how can I use that along with Grafana Agent?

**Comment by njtran** [comment] 2024-08-12 04:34
@varxnnn i'm not sure I understand your ask. I think the original ask was to understand why the metrics were showing up for one pod on the karpenter service, but not for the one that isn't the leader. if you want to grab the metrics of a particular pod that isn't the leader, scraping it from the pod directly should show the right metrics. Otherwise, what you'll see is the metrics of just the leader in the service. 

Since the original poster has acknowledged the recommendation, I'll close this out. @trojaond feel free to reopen if you think this isn't closed.

**Closed by njtran** 2024-08-12 04:34 UTC
Labels: kind/bug, needs-triage
