### ISSUE TITLE
Isn't working do-not-disrupt on pod

### ISSUE THREAD

**Issue by golaneduard** [kubernetes-sigs/karpenter#1168] opened 2024-04-04 12:14 UTC
### Description

**Observed Behavior**:
I have Jenkins configured on EKS, and I do have pipelines that create pods on Kubernetes as Jenkins workers, where the necessary commands are executed from pipeline. It is critical not to disrupt these pods, as this will cause the pipeline to fail. I've annotated these pods with (karpenter.sh/do-not-disrupt: "true"), but it isn't working as expected. Because Karpenter anyway is drainining the nodes where these pods are located if there are only a few pods and they do not occupy all of the node's resources.

**Expected Behavior**:
When on a Karpenter-managed node, pods are marked with an annotation (karpenter.sh/do-not-disrupt: "true") to prevent him from draining these nodes, even if there is just one.

**Reproduction Steps** (Please include YAML):
- pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: jenkins
  annotations:
    karpenter.sh/do-not-disrupt: "true"
spec:
    serviceAccount: jenkins-admin-user
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: jenkins-workers
              operator: In
              values:
              - "true"
      tolerations:
     - key: "dedicated"
       operator: "Equal"
       value: "sc-jenkins-workers"
       effect: "NoExecute"
  containers:
  - name: worker
    image: test-image:1.0
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: 5500Mi
        cpu: 3000m
      limit:
        memory: 5500Mi
        cpu: 3000m
  priorityClassName: high-priority
```
- nodepool.yaml
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: sandbox-jenkins-worker
spec:
  template:
    metadata:
      labels:
        jenkins-workers: "true"
    spec:
      taints:
        - key: dedicated
          value: sc-jenkins-workers
          effect: NoExecute
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["m"]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["m5", "m5a", "m5n", "m5ad", "m5d", "m5dn"]
          minValues: 5
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: [ "8" ]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: private
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h
```
- nodeclass.yaml
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: private
spec:
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 75Gi
        volumeType: gp3
        deleteOnTermination: true
  amiFamily: AL2
  role: "KarpenterNodeRole-eks-karpenter"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-karpenter"
        private: "true"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-karpenter"
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment] 2024-04-04 16:45
Based on your description it sounds like these nodes are being disrupted via consolidation, not expiration or drift. Are you able to verify this through logs or node events? Also, do you know what the age of these pods are roughly when they are disrupted? If the pods scheduled immediately before Karpenter began the drain operation, I believe you're hitting the race condition described in https://github.com/kubernetes-sigs/karpenter/issues/651. There's a roughly 300ms window between Karpenter validating a consolidation decision and the `karpenter.sh/disruption=disrupting:NoSchedule` taint being applied, during which pods could potentially schedule. 

If the disruption method isn't consolidation or the pods we're scheduled to the pod before the consolidation decision was made this could be something novel. Either way, are you able to share Karpenter logs?

**Comment by njtran** [comment] 2024-04-05 00:50
Seems like a duplicate of https://github.com/kubernetes-sigs/karpenter/issues/1167, closing this issue to track through that one.

**Closed by njtran** 2024-04-05 00:50 UTC
Labels: kind/bug, needs-triage
