### ISSUE TITLE
Limit The Maximum Number of Nodes in a Cluster

### ISSUE THREAD

**Issue by JeremyBolster** [kubernetes-sigs/karpenter#976] opened 2024-01-29 17:35 UTC
### Description

Related to #732 (But that is nodepool scoped)

**What problem are you trying to solve?**

At scale we would like to limit the number of nodes in our EKS clusters to a number that we have been able to performance test and validate.

Functionality:
* Ability to set a hard limit at a cluster level
* (Optional/Discussion) Concept of "pressure" to schedule larger nodes as the node count approaches node limit. This would sacrifice CPU and Memory to guarantee that clusters' node counts do not get too high.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jackfrancis** [comment] 2024-01-29 21:08
Would the appropriate inputs be various pressure points on control plane (apiserver load in particular) rather than a static node max number?

**Comment by njtran** [comment] 2024-01-29 21:44
I think this is a duplicate of https://github.com/kubernetes-sigs/karpenter/issues/745

**Closed** 2024-01-29 21:45 UTC
Labels: kind/feature, needs-triage

**Comment by JeremyBolster** [comment] 2024-01-29 22:31
> Would the appropriate inputs be various pressure points on control plane (apiserver load in particular) rather than a static node max number?

It's hard to say. We typically find different issues during different load tests, once one bottleneck is solved there is always another one. 

> Closing as a duplicate of https://github.com/kubernetes-sigs/karpenter/issues/745, feel free to re-open, comment there if you disagree.

yeah, similar enough to merge any discussion.

**Comment by cest-pas-faux** [comment] 2024-03-10 13:34
https://github.com/kubernetes-sigs/karpenter/issues/745
