### ISSUE TITLE
Missing: build instructions and dockerfile

### ISSUE THREAD

**Issue by infa-nang** [kubernetes-sigs/karpenter#902] opened 2023-12-20 07:54 UTC
### Description

I'm trying to fix some open issues and testing it out locally, but found out that there are no instructions present in the Makefile for building the code or creating a container image.

**Comment by Bryce-Soghigian** [comment] 2023-12-20 08:02
Here is a relevant thread for building container image and testing core changes using AWS Cloud Provider: https://kubernetes.slack.com/archives/C04JW2J5J5P/p1703017364076069

**Comment by Bryce-Soghigian** [comment] 2023-12-20 08:08
See Issue https://github.com/kubernetes-sigs/karpenter/issues/895 for an easier solution that is coming

**Comment by tzneal** [comment] 2023-12-20 11:12
I'll close this as a duplicate of #895. This is just the Karpenter library and can't currently be built into an image as there is no cloud provider specific logic (e.g. code that calls into the AWS APIs for creating virtual machines).

**Closed by tzneal** 2023-12-20 11:12 UTC
Labels: kind/bug, needs-triage
