### ISSUE TITLE
Force disruption/deprovision/termination of nodes after expiration or drift w/ grace period

### ISSUE THREAD

**Issue by jzuhusky** [kubernetes-sigs/karpenter#1205] opened 2024-04-24 15:14 UTC
### Description

**What problem are you trying to solve?**

When nodes have drifted or expired, deprovisioning can be blocked by a PDB: `Cannot deprovision Machine: PDB X prevents pod evictions` indefinitely. For infrastructure maintenance we generally *need* to cycle out these nodes - and we have cases where nodes are living indefinitely in a drifted or expired state. 

Nodes won't even be candidates for disruption because of single pods or unrelated PDBs in a multi-tenant environment - and as a result *all* workloads on the expired/drifted node will continue to run because of a problematic neighbor. 

_Would the maintainers consider a feature to force disruption / de-provisioning after a certain grace period once a node has drifted or expired?_

_Would the maintainers consider a feature where the node will be forcibly terminated if draining doesn't proceed after a certain amount of time because of problematic workloads that have PDBs with 0 allowed disruptions?_

If these features were implemented, obviously there'd need to be some warning to users when enabling this feature and what it might entail for running workloads. 

**How important is this feature to you?**

It would be a *really* nice to have. 

We also use AWS ASGs extensively, where it's possible to remove a node from a cluster once it's been in a terminating state for X period of time (by hook or by crook). Our SLA with users is that ungraceful disruption is possible if their workloads are left in a broken state and blocking node draining. 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment] 2024-04-25 07:36
This looks like a potential duplicate of #1047. Closing since this seems to meet the "force through PDBs" use-case after a given amount of time. Feel free to +1 that issue.

**Closed by jonathan-innis** 2024-04-25 07:36 UTC
Labels: kind/feature, needs-triage
